version: '3.8'
services:
  mysql:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mse-root
      MYSQL_DATABASE: mse
    restart: unless-stopped
    ports:
      - "3306:3306"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - "3000:3000"

volumes:
  mysql_data:
  grafana_data: