{
 "title": "monitor",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "query": "select distinct id from clusters"
   }
  ]
 },
 "panels": [
  {
   "title": "Configurations",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "mse",
     "rawSql": "SELECT * FROM mse.clusters where id = '$cluster_id'"
    }
   ]
  },
  {
   "title": "Resizing",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "mse",
     "rawSql": "SELECT event_time, is_resizing FROM mse.events where cluster_id = '$cluster_id' and $__timeFilter(event_time)"
    }
   ]
  },
  {
   "title": "Resource utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "mse",
     "rawSql": "SELECT event_time, cpu_utilization FROM mse.avg_metrics where cluster_id = '$cluster_id' and $__timeFilter(event_time)"
    },
    {
     "dataset": "mse",
     "rawSql": "SELECT event_time, (yarn_allocated_mem+yarn_reserved_mem) / yarn_total_mem as memory_utilization FROM mse.avg_metrics where cluster_id = '$cluster_id' and $__timeFilter(event_time)"
    },
    {
     "dataset": "mse",
     "rawSql": "SELECT event_time, (yarn_allocated_vcore+yarn_reserved_vcore) / yarn_total_vcore as vcore_utilization FROM mse.avg_metrics where cluster_id = '$cluster_id' and $__timeFilter(event_time)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "mse",
     "rawSql": "SELECT event_time, current_max_units FROM mse.events where cluster_id = '$cluster_id' and $__timeFilter(event_time)"
    },
    {
     "dataset": "mse",
     "rawSql": "SELECT event_time, target_max_units FROM mse.events where cluster_id = '$cluster_id' and $__timeFilter(event_time)"
    },
    {
     "dataset": "mse",
     "rawSql": "SELECT event_time, yarn_app_pending FROM mse.avg_metrics where cluster_id = '$cluster_id' and $__timeFilter(event_time)"
    },
    {
     "dataset": "mse",
     "rawSql": "SELECT event_time, yarn_app_running FROM mse.avg_metrics where cluster_id = '$cluster_id' and $__timeFilter(event_time)"
    },
    {
     "dataset": "mse",
     "rawSql": "SELECT event_time, yarn_active_nodes FROM mse.avg_metrics where cluster_id = '$cluster_id' and $__timeFilter(event_time)"
    }
   ]
  }
 ]
}